#ifndef  RTP_ENUM_H__
#define  RTP_ENUM_H__

enum RTPDirection
{
    EXTERNAL_PEER = 0,
    INTERNAL_PEER,
    MAX_DIRECTION
};

typedef enum cmd_type
{
    OFFER_CMD=0,
    ANSWER_CMD,
    DELETE_CMD,
    PING_CMD,

//  internal cmd
    PING_CHECK_CMD,
    MAX_CONTROL_CMD
}CONTROL_CMD;

enum CmdState
{
    CMDSESSION_STATE = 0,
    CMDSESSION_INIT_STATE,
    CMDSESSION_OFFER_PROCESSING_STATE,
    CMDSESSION_OFFER_PROCESSED_STATE,
    CMDSESSION_ANSWER_PROCESSING_STATE,
    CMDSESSION_ANSWER_PROCESSED_STATE,
    CMDSESSION_DELETE_STATE,
    CMDSESSION_MAX_STATE
};

enum Crypto_Suite
{
    AEAD_AES_256_GCM = 0,
    //AEAD_AES_128_GCM,
    //AES_256_CM_HMAC_SHA1_80,
    //AES_256_CM_HMAC_SHA1_32,
    //AES_192_CM_HMAC_SHA1_80,
    //AES_192_CM_HMAC_SHA1_32,
    //AES_CM_128_HMAC_SHA1_80,
    //AES_CM_128_HMAC_SHA1_32,
    //F8_128_HMAC_SHA1_80,
    //F8_128_HMAC_SHA1_32,
    MAX_CRYPTO_SUIT
};


enum RFC_RTP_PAYLOAD_TYPE_INDEX  // not payload type value
{
    PCMU_INDEX = 0,
    GSM_INDEX,
    G723_INDEX,
    DVI4_8000_INDEX,
    DVI4_16000_INDEX,
    LPC_INDEX,
    PCMA_INDEX,
    G722_INDEX,
    L16_1_CHANEL_INDEX,
    L16_2_CHANEL_INDEX,
    QCELP_INDEX,
    CN_INDEX,
    MPA_INDEX,
    G728_INDEX,
    DVI4_11025_INDEX,
    DVI4_22050_INDEX,
    G729_INDEX,
    CelB_INDEX,
    JPEG_INDEX,
    nv_INDEX,
    H261_INDEX,
    MPV_INDEX,
    MP2T_INDEX,
    H263_INDEX,
    MAX_PAYLOAD_TYPE_INDEX
};
#endif
